[project]
name = "maildealer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pre-commit>=4.1.0",
    "pyinstaller>=6.12.0",
    "selenium>=4.29.0",
]
